I, [2019-11-25T12:48:58.702792 #8269]  INFO -- default-vbox-xenial64: -----> Cleaning up any prior instances of <default-vbox-xenial64>
I, [2019-11-25T12:48:58.703081 #8269]  INFO -- default-vbox-xenial64: -----> Destroying <default-vbox-xenial64>...
I, [2019-11-25T12:48:58.703700 #8269]  INFO -- default-vbox-xenial64: Finished destroying <default-vbox-xenial64> (0m0.00s).
I, [2019-11-25T12:48:58.704009 #8269]  INFO -- default-vbox-xenial64: -----> Testing <default-vbox-xenial64>
I, [2019-11-25T12:48:58.704106 #8269]  INFO -- default-vbox-xenial64: -----> Creating <default-vbox-xenial64>...
I, [2019-11-25T12:49:00.262228 #8269]  INFO -- default-vbox-xenial64: Bringing machine 'default' up with 'virtualbox' provider...
I, [2019-11-25T12:49:00.579256 #8269]  INFO -- default-vbox-xenial64: ==> default: Box 'xenial64' could not be found. Attempting to find and install...
I, [2019-11-25T12:49:00.579615 #8269]  INFO -- default-vbox-xenial64:     default: Box Provider: virtualbox
I, [2019-11-25T12:49:00.579826 #8269]  INFO -- default-vbox-xenial64:     default: Box Version: >= 0
I, [2019-11-25T12:49:00.626508 #8269]  INFO -- default-vbox-xenial64: ==> default: Box file was not detected as metadata. Adding it directly...
I, [2019-11-25T12:49:00.626822 #8269]  INFO -- default-vbox-xenial64: ==> default: Adding box 'xenial64' (v0) for provider: virtualbox
I, [2019-11-25T12:49:00.631652 #8269]  INFO -- default-vbox-xenial64:     default: Downloading: xenial64
I, [2019-11-25T12:49:00.661086 #8269]  INFO -- default-vbox-xenial64: [KAn error occurred while downloading the remote file. The error
I, [2019-11-25T12:49:00.661212 #8269]  INFO -- default-vbox-xenial64: message, if any, is reproduced below. Please fix this error and try
I, [2019-11-25T12:49:00.661254 #8269]  INFO -- default-vbox-xenial64: again.
I, [2019-11-25T12:49:00.661301 #8269]  INFO -- default-vbox-xenial64: 
I, [2019-11-25T12:49:00.661380 #8269]  INFO -- default-vbox-xenial64: Couldn't open file /Users/catalina/Downloads/packer_xenial64/vagrant/.kitchen/kitchen-vagrant/default-vbox-xenial64/xenial64
E, [2019-11-25T12:49:00.706629 #8269] ERROR -- default-vbox-xenial64: Create failed on instance <default-vbox-xenial64>.
E, [2019-11-25T12:49:00.706791 #8269] ERROR -- default-vbox-xenial64: ------Exception-------
E, [2019-11-25T12:49:00.706872 #8269] ERROR -- default-vbox-xenial64: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2019-11-25T12:49:00.706971 #8269] ERROR -- default-vbox-xenial64: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'xenial64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'xenial64' (v0) for provider: virtualbox
    default: Downloading: xenial64
[K
STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/catalina/Downloads/packer_xenial64/vagrant/.kitchen/kitchen-vagrant/default-vbox-xenial64/xenial64
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1
E, [2019-11-25T12:49:00.707016 #8269] ERROR -- default-vbox-xenial64: ----------------------
E, [2019-11-25T12:49:00.707060 #8269] ERROR -- default-vbox-xenial64: ------Backtrace-------
E, [2019-11-25T12:49:00.707102 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/shell_out.rb:71:in `rescue in run_command'
E, [2019-11-25T12:49:00.707126 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/shell_out.rb:59:in `run_command'
E, [2019-11-25T12:49:00.707165 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:460:in `run_command'
E, [2019-11-25T12:49:00.707219 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:407:in `run'
E, [2019-11-25T12:49:00.707245 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:491:in `run_vagrant_up'
E, [2019-11-25T12:49:00.707267 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:112:in `create'
E, [2019-11-25T12:49:00.707288 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:485:in `public_send'
E, [2019-11-25T12:49:00.707314 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:485:in `block in perform_action'
E, [2019-11-25T12:49:00.707362 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:549:in `block in synchronize_or_call'
E, [2019-11-25T12:49:00.707397 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:547:in `synchronize'
E, [2019-11-25T12:49:00.707456 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:547:in `synchronize_or_call'
E, [2019-11-25T12:49:00.707491 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:514:in `block in action'
E, [2019-11-25T12:49:00.707520 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2019-11-25T12:49:00.707550 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:513:in `action'
E, [2019-11-25T12:49:00.707600 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:485:in `perform_action'
E, [2019-11-25T12:49:00.707632 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:394:in `create_action'
E, [2019-11-25T12:49:00.707656 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-11-25T12:49:00.707679 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-11-25T12:49:00.707701 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-11-25T12:49:00.707723 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `each'
E, [2019-11-25T12:49:00.707745 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-11-25T12:49:00.707775 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:162:in `verify'
E, [2019-11-25T12:49:00.707798 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:191:in `block in test'
E, [2019-11-25T12:49:00.708057 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2019-11-25T12:49:00.708090 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:187:in `test'
E, [2019-11-25T12:49:00.708119 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `public_send'
E, [2019-11-25T12:49:00.708150 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2019-11-25T12:49:00.708175 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-11-25T12:49:00.708194 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2019-11-25T12:49:00.708211 #8269] ERROR -- default-vbox-xenial64: ----End Backtrace-----
E, [2019-11-25T12:49:00.708228 #8269] ERROR -- default-vbox-xenial64: ---Nested Exception---
E, [2019-11-25T12:49:00.708251 #8269] ERROR -- default-vbox-xenial64: Class: Mixlib::ShellOut::ShellCommandFailed
E, [2019-11-25T12:49:00.708269 #8269] ERROR -- default-vbox-xenial64: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'xenial64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'xenial64' (v0) for provider: virtualbox
    default: Downloading: xenial64
[K
STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/catalina/Downloads/packer_xenial64/vagrant/.kitchen/kitchen-vagrant/default-vbox-xenial64/xenial64
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1
E, [2019-11-25T12:49:00.708291 #8269] ERROR -- default-vbox-xenial64: ----------------------
E, [2019-11-25T12:49:00.708335 #8269] ERROR -- default-vbox-xenial64: ------Backtrace-------
E, [2019-11-25T12:49:00.708364 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/shell_out.rb:71:in `rescue in run_command'
E, [2019-11-25T12:49:00.708389 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/shell_out.rb:59:in `run_command'
E, [2019-11-25T12:49:00.708412 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:460:in `run_command'
E, [2019-11-25T12:49:00.708431 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:407:in `run'
E, [2019-11-25T12:49:00.708463 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:491:in `run_vagrant_up'
E, [2019-11-25T12:49:00.708482 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.6.0/lib/kitchen/driver/vagrant.rb:112:in `create'
E, [2019-11-25T12:49:00.708519 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:485:in `public_send'
E, [2019-11-25T12:49:00.708568 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:485:in `block in perform_action'
E, [2019-11-25T12:49:00.708591 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:549:in `block in synchronize_or_call'
E, [2019-11-25T12:49:00.708609 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:547:in `synchronize'
E, [2019-11-25T12:49:00.708627 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:547:in `synchronize_or_call'
E, [2019-11-25T12:49:00.708642 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:514:in `block in action'
E, [2019-11-25T12:49:00.708661 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2019-11-25T12:49:00.708696 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:513:in `action'
E, [2019-11-25T12:49:00.708727 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:485:in `perform_action'
E, [2019-11-25T12:49:00.708791 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:394:in `create_action'
E, [2019-11-25T12:49:00.708817 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-11-25T12:49:00.708859 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-11-25T12:49:00.708908 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-11-25T12:49:00.708990 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `each'
E, [2019-11-25T12:49:00.709029 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-11-25T12:49:00.709055 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:162:in `verify'
E, [2019-11-25T12:49:00.709082 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:191:in `block in test'
E, [2019-11-25T12:49:00.709114 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2019-11-25T12:49:00.709166 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:187:in `test'
E, [2019-11-25T12:49:00.709199 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `public_send'
E, [2019-11-25T12:49:00.709242 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2019-11-25T12:49:00.709305 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-11-25T12:49:00.709366 #8269] ERROR -- default-vbox-xenial64: /Users/catalina/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2019-11-25T12:49:00.709402 #8269] ERROR -- default-vbox-xenial64: ----End Backtrace-----
